src/app/page.jsx
src/components/FllterDropdown/CardListPageEx.jsx
src/components/FllterDropdown/FillterDropdown.jsx

feat: 필터 드롭다운 추가

---

src/app/layout.js
src/app/page.jsx

---
css 디자인을 고침...
---
RootLayout 공통 css를 고침...
---
x

Chore: 진짜진짜 공통 css 끝(제발)

---

src/app/page.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

update: test

---

src/app/page.jsx
src/components/ui/Button.jsx

---
button 컴포넌트 추가했고 메인화면에서 테스트 하였습니다.
---
- 버튼 컴포넌트를 통합하였고 타입별로 불러와서 쓸수있게 만들었습니다.
---
-
-

feat: button 컴포넌트 추가

---

src/app/page.jsx
src/components/tag/GradeTag.jsx
src/components/tag/StatusTag.jsx

공통 Tag 컴포넌트 완성

---

src/app/page.jsx
src/app/test/page.jsx
src/components/ui/MyCardDetail.jsx

---
MyCardDetail 컴포넌트 구현했습니다
---
- 컴포넌트 구현하고 임시로 "/test" 주소 만들어서 확인용으로 넣어놨습니다
- 이 부분은 요소 하나하나가 데이터와 연결되는거라 예시로 작성했습니다. 
- 작업 3
---
- 
-

[김다은] feat: card/mycard-detail 컴포넌트

---

src/app/test/page.jsx
src/components/ui/BaseCard.jsx

---
--- 포토카드 반응형 부분 고정값 없애고 수정 
- 작업 1
- 작업 2
- 작업 3
---
- 아직 ui 디테일 수정 더 해야합니다. 
-

[김다은] update: 포토카드2차

---

src/app/home/page.jsx
src/components/ui/Button.jsx
src/components/ui/Pagination.jsx

---
페이지네이션 컴포넌트 추가 및 버튼 컴포넌트 일부 수정
---
- 작업 1 페이지네이션 컴포넌트 추가
- 작업 2 버튼 컴포넌트 커서 기능 추가, 넓이값을 full로 고정
- 작업 3
---
-
-

feat: ui pagination 추가 및 button 일부 수정

---

public/data/cards.json
src/app/common/page.jsx
src/app/home/page.jsx
src/components/ui/BaseCard.jsx
src/delay.js

Main Home Page 디자인 초안

---

src/app/test/page.jsx
src/components/tag/GradeTag.jsx
src/components/ui/BaseCard.jsx

---
--- 공통 마켓 페이지 버전 카드 기준으로만 ui 수정해서 추가 수정할 예정입니다. 
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: BaseCard 메인페이지 버전만 수정

---

src/app/test/page.jsx
src/components/ui/BaseCard.jsx

---
--- 포토카드: 교환제시목록 버전 맞춰서 수정 
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: 포토카드 3차 수정

---

src/app/common/page.jsx
src/components/ui/Button.jsx
src/components/ui/Profile.jsx
src/components/ui/ProfileMessage.jsx

---
---
- 작업 1 profile 컴포넌트 추가 
- 작업 2 button 잘못된 색상 수정
- 작업 3
---
-
-

feat: profile 컴포넌트 추가 및 button 색상 수정

---

src/components/ui/InputField.jsx
src/components/ui/PasswordField.jsx
src/components/ui/Search.jsx

---
--- search, inputfield, passwordfield 반응형 피그마 기준대로 수정
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: search, inputfield, passwordfield 반응형 설정

---

src/components/ui/BaseCards.jsx

헤더 컴포넌트, 홈페이지 수정, 스켈레톤 딜레이 타임 수정

---

src/actions/create-user.action.js
src/actions/login-user.action.js
src/app/layout.js
src/app/login/page.jsx
src/app/page.jsx

로그인 페이지 완성

---

src/app/home/[id]/page.jsx
src/components/FllterDropdown/FilterDropdown.jsx
src/components/HompageComponents/BaseCardsSection.jsx
src/components/ui/BaseCardList.jsx

---
- 로컬서버에서 불러오는거 배포서버에서 불러오게 바꿈, 
- 필터 드롭다운 수정
- 작업 1
- 작업 2
- 작업 3
---
-
-

fix: 로컬서버에서 불러오는거 배포서버에서 불러오게 바꿈, 필터 드롭다운 수정

---

src/app/home/[id]/page.jsx
src/components/HompageComponents/BaseCardsSection.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

fix:홈페이지 url 변경

---

src/app/home/[id]/page.jsx
src/lib/api/api-store.js

---
---
- 작업 1 store api 호출 수정
- 작업 2
- 작업 3
---
-
-

store api 호출 수정

---

src/app/home/[id]/page.jsx
src/components/HompageComponents/BaseCardsSection.jsx

- [x ] `fix:` 버그를 수정한 커밋
---
---
- 작업 1 라우트 및 빠진부분수정
- 작업 2
- 작업 3
---
-
-

라우트 및 빠진부분수정

---

src/app/home/[id]/page.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

카드 페이지 로그인페이지로  라우트 추가

---

src/app/layout.js
src/components/layout/Header.jsx
src/hooks/useLoginForm.js
src/providers/AuthProvider.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

헤더 로그아웃 완성

---

src/app/home/page.jsx
src/components/RandomPoint.jsx
src/components/RandomPointHomeTrigger.jsx
src/components/layout/Header.jsx

---
랜덤 포인트(랜덤 상자 뽑기) 기능을 홈 진입 시 자동 트리거 및 실시간 남은 시간 표시, 모달 최상단 고정 등 UX 개선 작업을 진행했습니다.
---
- 홈 진입 시 1시간/3회 조건에 따라 랜덤포인트 모달 자동 노출 트리거 구현
- 랜덤포인트 모달이 항상 화면 최상단(z-index)에서 보이도록 개선
- 남은 시간(1시간 제한) 실시간 갱신 기능 추가
- 랜덤 상자 뽑기 API 연동 및 에러 메시지 처리 개선
---

Feature/랜덤 포인트 API 연결 및 트리거 구현

---

src/components/RandomPoint.jsx
src/components/RandomPointHomeTrigger.jsx

---
로컬에서만 작동하던 포인트관련 API 수정
---
- localhost/3002 에서 배포 주소로 변경
---
-
-

포인트 API 주소 수정

---

src/components/layout/Header.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

헤더 텍스트 업데이트

---

src/components/layout/Header.jsx

---
헤더의 포인트 실시간 조회 되도록 변경
---
- 헤더의 포인트 1초마다 갱신
- 갱신시 로딩 메세지가 최초 1회에만 제공되게 변경
---
-
-

feat:헤더 포인트 실시간 조회

---

src/lib/api/fetch-client.js

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

baseurl 변경

---

src/app/test/page.jsx
src/components/CardSeller/SellerPage.jsx
src/components/PhotoCard/Exchange.jsx
src/components/ui/CardSeller.jsx

---
--- 해당 카드 판매자 입장에서 보이는 판매카드 상세 페이지, CardSeller 컴포넌트 맞춰서 수정 
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] feat: 판매카드 상세 페이지

---

src/app/my-gallery/page.jsx
src/components/ui/BaseCard.jsx

fix: 임시 저장

---

src/app/home/[id]/page.jsx
src/lib/api/fetch-client.js
src/middleware.js
src/providers/AuthProvider.jsx

---
---
- 작업 1 라우트 미들웨어 추가
- 작업 2 액세스토큰 쿠키로 이동
- 작업 3
---
-
-

라우트 미들웨어 추가 및 액세스토큰 쿠키로 이동

---

src/app/my-gallery/_components/MyPage.jsx
src/app/my-gallery/_components/OwnedCards.jsx
src/hooks/useFilter.js
src/lib/api/api-users.js
src/lib/api/fetch-client.js

---
쿼리 문자열 기능 끝
---
쿼리 문자열 기능 끝났고 디자인 더 봐야 함
---
-
-

쿼리 문자열 기능 끝

---

src/lib/api/fetch-client.js

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

fix: 커밋 테러 죄송... apiBaseUrl 수정

---

src/components/CardSeller/CardSellDetail.jsx
src/components/CardSeller/MyCardModal.jsx
src/components/CardSeller/SellerPage.jsx
src/components/ui/MyCardDetail.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: 임시로 업뎃

---

src/components/CardTrade/CardTrade.jsx
src/components/CardTrade/MyTradeCard.jsx
src/components/PhotoBuyer/PhotoBuyerDetail.jsx

---
--- 홈페이지/[id]구매자입장 연동
- 작업 1
- 작업 2
- 작업 3
---
-
-

feat: 홈페이지/[id]구매자입장 연동

---

src/components/CardTrade/CardTrade.jsx
src/components/PhotoBuyer/PhotoBuyerSection.jsx

---
---fix: 구매, 교환 요청시 모달 수정
- 작업 1
- 작업 2
- 작업 3
---
-
-

fix: 구매, 교환 요청시 모달 수정

---

src/components/CardSeller/CardSellDetail.jsx
src/components/CardSeller/MyCardModal.jsx
src/components/CardSeller/SellerPage.jsx
src/components/PhotoCard/Exchange.jsx
src/components/ui/CardSeller.jsx
src/lib/api/api-sale.js
src/lib/api/api-trade.js

---
--- 교환의 모든 기능 연결, 판매 내리기까지 연결 
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: 교환 거절, 승인, 판매 내리기 연결

---

package-lock.json
package.json
src/components/BottomSheet/BottomSheet.jsx
src/components/BottomSheet/FilterSheetControls.jsx
src/lib/api/fetch-client.js

---
--- 메인페이지 바텀시트 끝
- 작업 1
- 작업 2
- 작업 3
---
-
-

Feature/store 메인페이지 바텀시트 끝

---

src/app/my-gallery/_components/MyPage.jsx
src/components/BottomSheet/BottomSheet.jsx
src/components/BottomSheet/FilterTab.jsx
src/components/BottomSheet/Mygalleryfilter.jsx
src/hooks/useFilterSheet.js
src/lib/api/api-users.js
src/lib/api/fetch-client.js

---
---마이 갤러리에  바텀 시트 필터 추가
- 작업 1
- 작업 2
- 작업 3
---
-
-

Feature/store 마이 갤러리에  바텀 시트 필터 추가

---

src/app/for-my-sales/ForMySales.jsx
src/lib/api/api-users.js

---
style: 필터 매개변수 이름을 바꿨음
---
style: 필터 매개변수 이름을 바꿨음
---
style: 필터 매개변수 이름을 바꿨음

style: 필터 매개변수 이름을 바꿨음

---

src/app/for-my-sales/ForMySales.jsx
src/components/BottomSheet/BottomSheet.jsx
src/components/BottomSheet/FilterPanelSaleType.jsx
src/components/BottomSheet/FilterSheetControls.jsx
src/components/BottomSheet/FilterTab.jsx
src/components/BottomSheet/Mygalleryfilter.jsx
src/components/BottomSheet/SaleGaileryFilter.jsx
src/hooks/useFilter.js
src/hooks/useFilterSheet.js
src/lib/api/api-users.js
src/lib/api/fetch-client.js

---
---판매중인 마이판매 페이지 바텀시트 추가
- 작업 1
- 작업 2
- 작업 3
---
-
-

Feature/store 판매중인 마이판매 페이지 바텀시트 추가

---

src/components/ui/MyCardDetail.jsx

---
--- 판매 수정 때 닉네임 데이터 연결 안돼서 '나'로 나오는거 급하게 추가수정 올립니다
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: 판매수정때 닉네임 데이터 수정

---

src/app/for-my-sales/ForMySales.jsx

---
style: 안 쓰는 import문 삭제 등
---
style: 안 쓰는 import문 삭제 등
---
style: 안 쓰는 import문 삭제 등

style: 안 쓰는 import문 삭제 등

---

src/app/my-gallery/post/_components/File.jsx
src/app/my-gallery/post/_components/PostForm.jsx
src/lib/api/api-users.js

---
refactor: post page refactoring 끝
---
- 상태 수정: name, price... -> form 하나만 남김
- file에서 이름 빠져나가는 거 css 수정
- 모달 실패 뜬다고 했는데 안 고쳤고 뭔지 모르겠지만 정상적으로 뜸
---

refactor: post page refactoring 끝

---

src/app/my-gallery/post/_components/PostForm.jsx
src/hooks/usePostForm.js

---
refactor: postForm hook과 ui부분 나눔
---
refactor: postForm hook과 ui부분 나눔
---
refactor: postForm hook과 ui부분 나눔

refactor: postForm hook과 ui부분 나눔

---

src/components/CardBuyer/CardBuyer.jsx
src/components/PhotoBuyer/PhotoBuyerSection.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

fix:구매 모달 출력 내용 수정

---

src/components/CardBuyer/CardBuyer.jsx
src/components/CardTrade/MyTradeCard.jsx
src/components/PhotoBuyer/ExchangeCard.jsx
src/components/PhotoBuyer/PhotoBuyerSection.jsx
src/components/ui/Button.jsx
src/components/ui/Title.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

홈 디테일 페이지 ui이 업데이트

---

src/components/CardSeller/CardSellDetail.jsx
src/components/CardSeller/MyCardModal.jsx
src/components/ui/MyCardDetail.jsx

---
--- MyCardDetail ui 디테일 작업, 수정하기일 때 카드 이름 제대로 나오게 수정 
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: MyCardDetail ui 1차 작업

---

src/providers/AuthProvider.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

authprovider 재수정

---

src/components/BottomSheet/BottomSheet.jsx
src/components/BottomSheet/FilterPanelGenre.jsx
src/components/BottomSheet/FilterPanelGrade.jsx
src/components/BottomSheet/FilterPanelSale.jsx
src/components/BottomSheet/FilterPanelSaleType.jsx
src/components/CardTrade/CardTrade.jsx
src/components/CardTrade/MyTradeCard.jsx
src/components/PhotoBuyer/ExchangeCard.jsx
src/components/PhotoBuyer/PhotoBuyerDetail.jsx
src/components/PhotoCard/ExchangeCancel.jsx
src/hooks/useFilterSheet.js
src/lib/api/fetch-client.js

---
---구매페이지 ui수정 및 교환하기 필터 적용
- 작업 1
- 작업 2
- 작업 3
---
-
-

Feature/store 구매페이지 ui수정 및 교환하기 필터 적용

---

src/components/BottomSheet/Mygalleryfilter.jsx
src/components/CardTrade/CardTrade.jsx
src/components/CardTrade/MyTradeCard.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

feat:교환 요청할때 카드 상세페이지 추가

---

src/components/modal/StateModal.jsx
src/lib/api/fetch-client.js

---
feat: 모달 모바일일 때 모양 바꿈
---
feat: 모달 모바일일 때 모양 바꿈
---
feat: 모달 모바일일 때 모양 바꿈

feat: 모달 모바일일 때 모양 바꿈

---

src/app/for-my-sales/ForMySales.jsx
src/app/my-gallery/_components/MyPage.jsx
src/app/my-gallery/post/page.jsx
src/components/modal/StateModal.jsx

---
css 수정
---
- 페이지들: mobile일 때 header와 안 달라붙에 my 줌
---

style: css 수정

---

src/components/CardSeller/CardSellDetail.jsx
src/components/CardSeller/MyCardModal.jsx

---
--- 판매 카드 모달 외부 배경 클릭 시에도 닫히기 기능 추가 
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: 김다은 버그 4차 수정

---

src/components/modal/NotiModal.jsx

---
모달 - 판매 내리기 추가
---
모달 - 판매 내리기 추가
---
모달 - 판매 내리기 추가

feat: 모달 - 판매 내리기 추가

---

src/components/CardSeller/EditCardModal.jsx
src/components/CardSeller/SellerPage.jsx
src/components/ui/CardSeller.jsx

---
--- 수정하기 바로 반영되도록 수정 
- 작업 1
- 작업 2
- 작업 3
---
-
-

[김다은] update: 김다은 버그 5차 수정

---

src/components/ui/BaseCard.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

price 쉼표 추가

---

src/app/for-my-sales/ForMySales.jsx
src/components/PhotoCard/ForSale.jsx

---
---
- 작업 1
- 작업 2
- 작업 3
---
-
-

fix: 링크 다시 수정
